import type { Metadata } from "next";
import './globals.css'
//import '@/app/ui/global.css';

export const metadata: Metadata = {
  title: "Avni Uplabdhee",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[url('/bg/paper-texture.png')] bg-cover bg-fixed bg-center bg-no-repeat">
        {children}
      </body>
    </html>
  );
}
